In [1]:
import pretty_midi
import numpy as np
import matplotlib.pyplot as plt
import pathlib
import yaml

from pitch_mapping import pitch_distances, valid_pitch_selection, pitch_mapping, NoUntunedPercussionTrackFound

with open('./valid_pitches.yaml','r') as f:
    valid_pitches = yaml.safe_load(f)

In [2]:
note_pitches = np.random.randint(0,127,100)
note_pitches

array([ 10, 111,  11,  62,  18,  10,  99,  40, 109,  26,  86,  40,  23,
        23,  53,  53,  26,  78,   9, 120,  65,  99,  54,  28,  48,  13,
        48,  69,  40,   8,  77,  82,  90,  36, 117,  35,  88,  57,   0,
        20,   5, 115,  29,  93, 110, 111,  14,  47,  83,  49,  60, 123,
        44,  74,  67,  11,  90,  52, 122,  35,  16,  29,  73,  33,  34,
         7,  65,  84,   6,   5,  34,  78,  66, 116, 101,   0,  40,  12,
        24,   7, 122,  80, 125,  12,  75,  72,   8,  61,  11, 110, 110,
        78,  18,  35,  46,  80,  35,  41, 111,  10])

In [3]:
instrument_valid_pitches = np.array(valid_pitches[100]['Valid_pitches'])
instrument_valid_pitches

array([48, 50, 52, 53])

In [4]:
distances = pitch_distances(note_pitches[0],instrument_valid_pitches)
note_valid_pitch = valid_pitch_selection(instrument_valid_pitches,distances)
print(distances)
print(f'Note pitch = {note_pitches[0]}')
print(f'Minimum distance = {distances.min()}')
print(f'Note valid pitch = {note_valid_pitch}')

[[38 40 42 43]
 [26 28 30 31]
 [14 16 18 19]
 [ 2  4  6  7]
 [10  8  6  5]
 [22 20 18 17]
 [34 32 30 29]
 [46 44 42 41]
 [58 56 54 53]
 [70 68 66 65]]
Note pitch = 10
Minimum distance = 2
Note valid pitch = 48


In [5]:
for n,note_pitch in enumerate(note_pitches):
    distances = pitch_distances(note_pitch,instrument_valid_pitches)
    note_valid_pitch = valid_pitch_selection(instrument_valid_pitches,distances)
    print(f'Note number {n+1}>> minimum distance = {distances.min()}, valid_pitch = {note_valid_pitch}')

Note number 1>> minimum distance = 2, valid_pitch = 48
Note number 2>> minimum distance = 1, valid_pitch = 50
Note number 3>> minimum distance = 1, valid_pitch = 48
Note number 4>> minimum distance = 0, valid_pitch = 50
Note number 5>> minimum distance = 1, valid_pitch = 53
Note number 6>> minimum distance = 2, valid_pitch = 48
Note number 7>> minimum distance = 1, valid_pitch = 50
Note number 8>> minimum distance = 0, valid_pitch = 52
Note number 9>> minimum distance = 1, valid_pitch = 48
Note number 10>> minimum distance = 0, valid_pitch = 50
Note number 11>> minimum distance = 0, valid_pitch = 50
Note number 12>> minimum distance = 0, valid_pitch = 52
Note number 13>> minimum distance = 1, valid_pitch = 48
Note number 14>> minimum distance = 1, valid_pitch = 48
Note number 15>> minimum distance = 0, valid_pitch = 53
Note number 16>> minimum distance = 0, valid_pitch = 53
Note number 17>> minimum distance = 0, valid_pitch = 50
Note number 18>> minimum distance = 1, valid_pitch = 53
N

In [6]:
midifiles = [file for file in pathlib.Path('../../targetMIDI/MIDI/expressiveSOD/Kunstderfuge/').glob('*')]

midi_data = pretty_midi.PrettyMIDI(str(midifiles[13]))

try:
    mapped_midi_data = pitch_mapping(midi_data,valid_pitches)
except NoUntunedPercussionTrackFound:
    print('No untuned percussion in this file')

In [10]:
untuned_percussion_index = [instrument.name for instrument in midi_data.instruments].index('untunedpercussion')
for n in range(len(mapped_midi_data.instruments[untuned_percussion_index].notes)):
    original_pitch = midi_data.instruments[untuned_percussion_index].notes[n].pitch
    mapped_pitch = mapped_midi_data.instruments[untuned_percussion_index].notes[n].pitch
    print(f'Note {n+1}>> Original pitch: {original_pitch}, Mapped pitch: {mapped_pitch}')

Note 1>> Original pitch: 38, Mapped pitch: 50
Note 2>> Original pitch: 38, Mapped pitch: 50
Note 3>> Original pitch: 38, Mapped pitch: 50
Note 4>> Original pitch: 38, Mapped pitch: 50
Note 5>> Original pitch: 38, Mapped pitch: 50
Note 6>> Original pitch: 38, Mapped pitch: 50
Note 7>> Original pitch: 38, Mapped pitch: 50
Note 8>> Original pitch: 38, Mapped pitch: 50
Note 9>> Original pitch: 38, Mapped pitch: 50
Note 10>> Original pitch: 38, Mapped pitch: 50
Note 11>> Original pitch: 38, Mapped pitch: 50
Note 12>> Original pitch: 38, Mapped pitch: 50
Note 13>> Original pitch: 38, Mapped pitch: 50
Note 14>> Original pitch: 38, Mapped pitch: 50
Note 15>> Original pitch: 38, Mapped pitch: 50
Note 16>> Original pitch: 38, Mapped pitch: 50
Note 17>> Original pitch: 38, Mapped pitch: 50
Note 18>> Original pitch: 38, Mapped pitch: 50
Note 19>> Original pitch: 38, Mapped pitch: 50
Note 20>> Original pitch: 38, Mapped pitch: 50
Note 21>> Original pitch: 38, Mapped pitch: 50
Note 22>> Original pit